Revert "LE-A: Handle either Media or Voice only profile connections(2/2)."
Depends on proprietary classes.

vendor/qcom/opensource/commonsys/packages/apps/Bluetooth/src/com/android/bluetooth/le_audio/LeAudioService.java:79: error: cannot find symbol
import com.android.bluetooth.apm.DeviceProfileMap;
                                ^
  symbol:   class DeviceProfileMap
  location: package com.android.bluetooth.apm
1 error

This reverts commit 2d6465ae05da0bfa8e6ac10f095f76b2b7dffe1f.